version: '3'
services:
  openbas-dev-pgsql:
    container_name: openbas-dev-pgsql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    ports:
      - "5432:5432"
    restart: unless-stopped
  openbas-test-pgsql:
    container_name: openbas-test-pgsql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    ports:
      - "5433:5432"
    restart: unless-stopped
  openbas-dev-minio:
    container_name: openbas-dev-minio
    image: minio/minio:latest
    ports:
      - "10000:9000"
      - "10001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
  openbas-dev-rabbitmq:
    container_name: openbas-dev-rabbitmq
    image: rabbitmq:4.0-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  openbas-dev-caldera:
    container_name: openbas-dev-caldera
    image: openbas/caldera-server:5.0.0
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://localhost:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml
  openbas-telemetry-jaeger:
    container_name: openbas-telemetry-jaeger
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4317:4317"
